apiVersion: skaffold/v2beta17
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/kubernates/*
build:
  local:
    push: false
  artifacts:
    - image: fabianosbaratta/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: fabianosbaratta/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: fabianosbaratta/customers
      context: customers
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: fabianosbaratta/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .