apiVersion: v1
kind: PersistentVolume
metadata:
  name: tickets-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb/3"