apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-mongo-depl
  labels:
    app: api-mongo
spec:
  replicas: 1
  serviceName: 'api-mongo'
  selector:
    matchLabels:
      app: api-mongo
  template:
    metadata:
      labels:
        app: api-mongo
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: api-mongo
          image: mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: task-pv-storage
          resources: 
            requests:
              cpu: "50m"
              memory: "128Mi"              
            limits:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-mongo-srv
spec:
  type: LoadBalancer
  selector:
    app: api-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017