apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tickets-mongo-depl
  labels:
    app: tickets-mongo
spec:
  replicas: 1
  serviceName: 'tickets-mongo'
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      volumes:
        - name: tickets-pv-storage
          persistentVolumeClaim:
            claimName: tickets-pv-claim
      containers:
        - name: tickets-mongo
          image: mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: tickets-pv-storage
          # resources: 
          #   requests:
          #     cpu: "50m"
          #     memory: "128Mi"              
          #   limits:
          #     cpu: "100m"
          #     memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017